//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class computers
    {
        public int id { get; set; }
        public Nullable<int> idClass { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual classes classes { get; set; }
    }
}
